# Variable Group 'Config Variables' was defined in the Variables tab
# Variable Group 'KeyVault Variable for QA environment' was defined in the Variables tab
trigger:
  branches:
    exclude:
    - refs/heads/master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'ARM Template deployment: Resource Group scope'
    inputs:
      ConnectedServiceName: 5b7a5194-25d1-4b3f-8ad3-c3073ab9a0eb
      subscriptionName: 8aa224f7-539d-46b5-a81f-385ad15a78ab
      resourceGroupName: pcs-rg-payroll360-project
      location: East US
      csmFile: Logic-App/LogicApp.json
      overrideParameters: -office365_1_Connection_Name "office365" -office365_1_Connection_DisplayName "shaikhm@pcscapital.com" -sql_2_Connection_Name "sql-1" -sql_2_Connection_DisplayName "ConfigConn" -sql_2_server "$(serverName).database.windows.net" -sql_2_database "$(DBname1)" -sql_2_username "$(administratorLogin)" -sql_2_password "$(administratorLoginPassword)" -sql_2_encryptConnection false -sql_2_privacySetting Organizational -sql_2_sqlConnectionString "Server=tcp:$(serverName).database.windows.net,1433;Initial Catalog=$(DBname1);Persist Security Info=False;User ID=$(administratorLogin);Password=$(administratorLoginPassword);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" -sql_1_Connection_Name "sql" -sql_1_Connection_DisplayName "test" -sql_1_server "$(serverName).database.windows.net" -sql_1_database "$(DBname1)" -sql_1_username "$(administratorLogin)" -sql_1_password "$(administratorLoginPassword)" -sql_1_encryptConnection false -sql_1_privacySetting Organizational -sql_1_sqlConnectionString "Server=tcp:$(serverName).database.windows.net,1433;Initial Catalog=$(DBname1);Persist Security Info=False;User ID=$(administratorLogin);Password=$(administratorLoginPassword);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" -azureblob_1_Connection_Name "azureblob" -azureblob_1_Connection_DisplayName "ConnectBlob" -azureblob_1_accountName "stpayroll360$(env)001" -azureblob_1_accessKey "DefaultEndpointsProtocol=https;AccountName=stpayroll360qa001;AccountKey=9WLBIUk6ndW+WmyvqP7fy4FYMZDgy0z0dIjvGRP+sdzb4YifR42qwV5Erh0VoxNLfgD+s6Qa/Bt7Fz6LeMAgtQ==;EndpointSuffix=core.windows.net" -azureblob_1_authType basic -azureblob_1_privacySetting Organizational -LogicAppLocation "eastus" -LogicAppName "pcs-la-email-payroll360-$(env)"
      deploymentMode: Validation
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: Logic-App
      Contents: '**.json'
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
